kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {DB_PV_CLAIM_NAME}
  namespace: {NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {DB_STORAGE_SIZE}
